"""Constants for the Cankut Extron integration."""

DOMAIN = "cankut_extron"

DEFAULT_HOST = "192.168.4.74"
DEFAULT_PORT = 5000

PLATFORM_SWITCH = "switch"
PLATFORMS = [PLATFORM_SWITCH]

PROJECTOR_ON_COMMAND = "PROJECTOR_ON"
PROJECTOR_OFF_COMMAND = "PROJECTOR_OFF"
PROJECTOR_STATUS_COMMAND = "PROJECTOR_STATUS"

PROJECTOR_STATE_ON = "PROJECTOR_STATE:ON"
PROJECTOR_STATE_OFF = "PROJECTOR_STATE:OFF"

RECONNECT_DELAY = 5
